Hints and possible issues
=========================

.. contents:: **Contents**


Download registered as completed, but hash check returned unfinished chunks
-------------------------------------

* `From manual <https://github.com/rakshasa/rtorrent/wiki/User-Guide#common-error-messages>`_: "This message is caused by deleting/modifying the downloaded file after a torrent is marked as complete. You could set the ``create/resize queued`` flags on all files of the torrent by pressing ``^e`` in main view":

  * ``^k`` + ``^e`` + ``^s`` (it will start to download the whole torrent again, probably :( )

* Maybe the data file/directory couldn't be moved to the target directory

  * there is already a file/directory with the same name: move or delete the previous download , move this new one, and start it (the queue script and rtorrent config should handle this situation now.)


Inactive: Tracker: [Could not parse bencoded data] and torrent is in Closed state
-------------------------------------

* wait till the tracker in question doesn't emit HTTP 500 responses any more, which is the most common cause for that error message

* if there's no problem with the tracker (other torrents working well), then you have to manually stop then start the torrent:

  * ``d.stop=`` and ``d.start=``  (or with ``^k`` + ``^s`` + ``SHIFT+I``)


Rotating part of queue script isn't working:
-------------------------------------

* either we ran out of disk space

* or ``rtorrent`` isn't running

* or ``rtorrent.lock`` file (in ``.session`` dir) is empty (thanks to we ran out space previously)!!!!!

  * stop ``rtorrent`` manually with ``kill -s INT $pid`` , then start it again! (then check the contents of lock file)


Stop downloading of a torrent but still uploading it
-------------------------------------

* set the priority of all the files to off


Hash-checking existing data for seeding purposes
-------------------------------------

* place ``hash-checkable data`` into ``incomplete`` directory and its ``meta`` file into one the sub-directories of ``.downloading`` directory
* hash-checking will start immediately


Changing announce URL of a tracker
-------------------------------------

Sometimes a regular tracker URL is changed for whatever reason and as a result, all the existing torrents stop working. Although there's an example how to change it on-the-fly with the help of `rtcontrol <http://pyrocore.readthedocs.io/en/latest/advanced.html#executing-xmlrpc-commands>`_ utility, but after several restarts it didn't seem to be a reliable way to deal with this problem. If it works for you, then problem solved already. :)

What definitely will work is modifying the actual ``*.torrent`` and ``*.torrent.libtorrent_resume`` files in ``.session`` directory for every affected torrents:

* stop ``rtorrent`` (also disable any script in ``cron`` that can start it)
* make a backup of the whole ``.session`` directory first
* search for ``old/tracker/url`` in ``.session`` directory and copy them somewhere (also backup them as well)
* change these ULRs to the new one: beware that you have to modify the integer before it (`Bencode <https://en.wikipedia.org/wiki/Bencode>`_)
* try it out with only 1, if it works then you can modify the rest
* copy back all the modified ``*.torrent`` and ``*.torrent.libtorrent_resume`` files into ``.session`` directory
* start ``rtorrent`` (also enable the previously disabled scripts in ``cron``)
